AWSTemplateFormatVersion: "2010-09-09"

Resources:
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: grp6-datalakexxx

  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: grp6-datawarexxx

  IngestionGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: crime-ingestion
      Role: arn:aws:iam::234578692179:role/LabRole
      GlueVersion: 4.0
      NumberOfWorkers: 5
      Timeout: 30
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: s3://grp-6-py-scripts/ingesion_script.py
      DefaultArguments:
        "--job-language": "python"
      ExecutionProperty:
        MaxConcurrentRuns: 1

  TransformationGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: crime-transformation
      Role: arn:aws:iam::234578692179:role/LabRole
      GlueVersion: 4.0
      NumberOfWorkers: 5
      Timeout: 30
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: s3://grp-6-py-scripts/transform.py
      DefaultArguments:
        "--job-language": "python"
      ExecutionProperty:
        MaxConcurrentRuns: 1

  GlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: ETL Job
      MaxConcurrentRuns: 1
      Name: crime-workflow

  GlueTriggerImport:
    Type: AWS::Glue::Trigger
    DependsOn:
      - GlueWorkflow
      - IngestionGlueJob
    Properties:
      Actions:
        - JobName: !Ref IngestionGlueJob
      Description: Triggers the Import Jobs
      Name: gluetriggerimport
      Type: ON_DEMAND
      WorkflowName: crime-workflow

  GlueTriggerTransform:
    Type: AWS::Glue::Trigger
    DependsOn:
      - GlueWorkflow
      - TransformationGlueJob
      - GlueTriggerImport
    Properties:
      Actions:
        - JobName: !Ref TransformationGlueJob
      Description: Triggers the transformation job 
      Name: gluetriggertransform
      Predicate:
        Conditions:
          - JobName: !Ref IngestionGlueJob
            LogicalOperator: EQUALS
            State: SUCCEEDED
        Logical: AND
      Type: CONDITIONAL
      StartOnCreation: True
      WorkflowName: crime-workflow
